version: "2"
services:

 es:
   image: elasticsearch:5.6
   environment:
     - bootstrap.memory_lock=true
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
   volumes:
     - es-data:/usr/share/elasticsearch/data
   ports:
     - 9200
   networks:
     - totara
volumes:
    es-data:

networks:
  totara:
